version: 1
update_configs:
  - package_manager: 'javascript'
    default_reviewers: ''
    directory: '/'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'all'
